name: zero
description: "Minimalistic calculator app"
publish_to: "none"
version: 1.0.6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  desktop_window: ^0.4.2
  msix: ^3.16.8
  math_expressions: ^2.7.0
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

flutter:
  uses-material-design: true

msix_config:
  display_name: Zero
  publisher_display_name: AS
  identity_name: com.as.project-zero
  msix_version: 1.0.6.0
  logo_path: windows/runner/resources/app_icon.ico
